server:
  port: 9030
  compression:
      enabled: true
      mime-types: application/json,application/xml,text/html,text/xml,text/plain

logging:
  path: /home/crm/jenkins/workspace/server-frontend
  file: backend.log
  level:
    org.slf4j: 'DEBUG'

spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate

    datasource:
        url: jdbc:mysql://localhost:3306/server2
        username: server2
        password: server2
        driver-class-name: com.mysql.cj.jdbc.Driver