server:
  port: 9030
  compression:
      enabled: true
      mime-types: application/json,application/xml,text/html,text/xml,text/plain

frontend:
  url: http://localhost:9000
  url-allowed: '*'

logging:
  path: /var/log
  file: server.log
  level:
    org.slf4j: 'INFO'

spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate

    datasource:
        url: jdbc:mysql://localhost:3306/server2
        username: server2
        password: server2
        driver-class-name: com.mysql.cj.jdbc.Driver