server:
  port: 9030
  compression:
      enabled: true
      mime-types: application/json,application/xml,text/html,text/xml,text/plain

frontend:
  url: http://localhost:9000
  url-allowed: '*'

logging:
  path: /var/log
  file: server.log
  level:
    org.slf4j: 'DEBUG'